FORMAT: 1A
HOST: https://sea-drone-center.herokuapp.com/

# Sea Drone Center

Sea Drone Center is the front and backend for our DAB Sea Drones.

## Boat Collection [/api/boats]

### List All Boats [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "fence": [
                    [
                        12.201,
                        51.2221
                    ],
                    [
                        12.20001,
                        51.222267
                    ],
                    [
                        14.214501,
                        52.912267
                    ]
                ],
                "position": [
                    12.2001,
                    51.222
                ],
                "heading": 0,
                "speed": 5,
                "wayPoints": [
                    [
                        12.201,
                        51.2221
                    ],
                    [
                        12.20001,
                        51.222267
                    ],
                    [
                        14.214501,
                        52.912267
                    ]
                ],
                "command": "SEARCH"
            }
        ]

### Update A Boat [POST]

Update our boats using this route.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /boats/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }