/**
 * Sea Drone Center API
 * The DAB Sea Drone Center API is used by our app and saves and sends data to our sea drones. [http://sea-drone-center.herokuapp.com](http://sea-drone-center.herokuapp.com). 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Boat (
  id: Option[Long] = None,
  fence: Option[Seq[ERRORUNKNOWN]] = None
) extends ApiModel


